import Image from "next/image";

export default function Socialicons() {
  return (
    <main className="grid grid-cols-2 md:grid-cols-4 gap-5 place-items-center content-center">
      <a
        href="https://www.linkedin.com/in/divy-zala-272a2322a/"
        target="_blank"
        rel="noreferrer"
        className="social-icons"
      >
        <Image
          alt=""
          height={70}
          width={70}
          src={"https://img.icons8.com/color/48/undefined/linkedin.png"}
        />
        <h2>LinkedIn</h2>
      </a>
      <a
        href="https://github.com/Divy31245"
        target="_blank"
        rel="noreferrer"
        className="social-icons"
      >
        <Image
          alt=""
          height={70}
          width={70}
          src={"https://img.icons8.com/ios-glyphs/30/undefined/github.png"}
        />
        <h2>Github</h2>
      </a>
      <a
        href="https://twitter.com/divy_zala"
        target="_blank"
        rel="noreferrer"
        className="social-icons"
      >
        <Image
          alt=""
          height={70}
          width={70}
          src={"https://img.icons8.com/color/48/undefined/twitter--v1.png"}
        />
        <h2>Twitter</h2>
      </a>
      <a
        href="https://www.facebook.com/divy.zala.96/"
        target="_blank"
        rel="noreferrer"
        className="social-icons"
      >
        <Image
          alt=""
          height={70}
          width={70}
          src={"https://img.icons8.com/color/48/undefined/facebook-new.png"}
        />
        <h2>Facebook</h2>
      </a>
      <a
        href="https://stackoverflow.com/users/19262583/divy-zala"
        className="social-icons"
        target="_blank"
        rel="noreferrer"
      >
        <Image
          alt=""
          height={70}
          width={70}
          src={"https://img.icons8.com/color/48/undefined/stackoverflow.png"}
        />
        <h2>Stack-overflow</h2>
      </a>
      <a
        href="mailto:divyzalab@gmail.com"
        className="social-icons"
        target="_blank"
        rel="noreferrer"
      >
        <Image
          alt=""
          height={70}
          width={70}
          src={"https://img.icons8.com/color/48/undefined/gmail--v1.png"}
        />
        <h2>Email</h2>
      </a>
      <a
        href="tel:+91-9737689805"
        className="social-icons"
        target="_blank"
        rel="noreferrer"
      >
        <Image
          alt=""
          height={70}
          width={70}
          src={"https://img.icons8.com/color/48/undefined/phone.png"}
        />
        <h2>Phone</h2>
      </a>
      <a
        href="tel:+91-9737689805"
        className="social-icons"
        target="_blank"
        rel="noreferrer"
      >
        <Image
          alt=""
          height={70}
          width={70}
          src={"https://img.icons8.com/color/48/undefined/instagram-new--v1.png"}
        />
        <h2>Instagram</h2>
      </a>
    </main>
  );
}
