import Head from "next/head";
import LeftSidebar from "../components/sidebar-left/sidebar-left";
import RightSidebar from "../components/sidebar-right/sidebar-right";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex ">
        <LeftSidebar />
        <RightSidebar />
      </main>
      
    </div>
  );
}
